### PR TITLE
KernelSU support

### PR DESCRIPTION
**Pull request by fisuri**

### CODE REVIEW

**Comment by elizabethangelalorenza** [comment]
Never

**Comment by fisuri** [comment]
> Never

Why?

**Comment by elizabethangelalorenza** [comment]
> > Never
> 
> Why?

1. Idc
2. Official rules

**Comment by Reinazhard** [comment]
> > Never
> 
> Why?

https://git.zx2c4.com/kernel-assisted-superuser/about/

shipping root on production build is never recommended by anyone.

**Comment by fisuri** [comment]
> > > Never
> > 
> > 
> > Why?
> 
> https://git.zx2c4.com/kernel-assisted-superuser/about/
> 
> shipping root on production build is never recommended by anyone.

Okay, I get it

**Pull request closed without merging**
